server:
  port: 8899
  servlet:
    context-path: /smartland

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    com:
      guotu:
        gt:
          mapper : debug