server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pratice?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.guotu.gt.domain

#showSql
logging:
  level:
    com:
      guotu:
        gt:
          mapper : debug