server:
  port: 8899
  servlet:
    context-path: /smartland

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://175.6.122.21:10088/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#showSql
logging:
  level:
    com:
      guotu:
        gt:
          mapper : debug